---
groups:
  - name: node_exporter_alerts
    rules:
      - alert: HighCPUUsage
        expr: >
          100 - (avg by (instance)
          (rate(node_cpu_seconds_total{mode="idle"}[1m])) * 100) > 80
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: >
            Высокая загрузка CPU на {{ $labels.instance }}
          description: >
            CPU выше 80% в течение 1 минуты на {{ $labels.instance }}
