---
name: CI
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Клонирование репозитория
        uses: actions/checkout@v4

      - name: Установка promtool и yamllint
        run:
          sudo apt-get update
          sudo apt-get install -y prometheus yamllint

      - name: Установка amtool (Alertmanager CLI)
        run: >
          wget https://github.com/prometheus/alertmanager/releases/download/v0.26.0/alertmanager-0.26.0.linux-amd64.tar.gz
          tar -xzf alertmanager-0.26.0.linux-amd64.tar.gz
          sudo mv alertmanager-0.26.0.linux-amd64/amtool /usr/local/bin/amtool

      - name: Проверка YAML-файлов
        run: yamllint .github docker-compose.yml prometheus alertmanager

      - name: Проверка конфигурации Prometheus
        run: promtool check config prometheus/prometheus.yml

      - name: Проверка правил алертов
        run: promtool check rules prometheus/alert.rules.yml

      - name: Проверка конфигурации Alertmanager
        run:
          if [ -f alertmanager/alertmanager.yml ]; then
            amtool check-config alertmanager/alertmanager.yml
          else
            echo "alertmanager.yml отсутствует, пропускаем"
          fi
